version: '3.8'

services:
  db:
    image: 'mysql:8.3'
    ports:
      - '3306:3306'
    env_file:
      - config/db.env
    volumes:
      - 'mysqlvol:/data'
    networks:
      - desafiofrequencia
    restart: always
      
  desafiofrequenciaapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:80'
    networks:
      - desafiofrequencia
    restart: always
    depends_on:
      - db

networks:
  desafiofrequencia:
    driver: bridge

volumes:
  mysqlvol:
